apiVersion: v1
kind: Service
metadata:
  name: {{ include "chainke.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chainke.labels" . | nindent 4 }}
    {{- include "chainke.backendSelectorLabels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "chainke.backendSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.backendPort }}
      targetPort: {{ .Values.backend.containerPort }}
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: {{ .Values.backend.containerPort }}
---
{{- if .Values.agent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chainke.fullname" . }}-agent
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chainke.labels" . | nindent 4 }}
    {{- include "chainke.agentSelectorLabels" . | nindent 4 }}
  annotations:
    service.kubernetes.io/load-balancer-type: "Internal"
spec:
  type: ClusterIP
  selector:
    {{- include "chainke.agentSelectorLabels" . | nindent 4 }}
  ports:
    - name: agent-http
      protocol: TCP
      port: {{ .Values.service.agentPort }}
      targetPort: {{ .Values.agent.containerPort }}
    - name: metrics
      protocol: TCP
      port: 9091
      targetPort: {{ .Values.agent.containerPort }}
{{- end }}
