"""initial_schema

Revision ID: 02c9e16c4b58
Revises: 
Create Date: 2026-05-27 07:28:25.517009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c9e16c4b58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_requests_id'), table_name='invoice_requests')
    op.drop_index(op.f('ix_invoice_requests_order_id'), table_name='invoice_requests')
    op.drop_index(op.f('ix_invoice_requests_user_id'), table_name='invoice_requests')
    op.drop_table('invoice_requests')
    op.drop_index(op.f('ix_admin_config_id'), table_name='admin_config')
    op.drop_index(op.f('ix_admin_config_key'), table_name='admin_config')
    op.drop_table('admin_config')
    op.drop_index(op.f('idx_balance_logs_user_time'), table_name='balance_logs')
    op.drop_index(op.f('ix_balance_logs_id'), table_name='balance_logs')
    op.drop_index(op.f('ix_balance_logs_user_id'), table_name='balance_logs')
    op.drop_table('balance_logs')
    op.drop_index(op.f('ix_admin_config_logs_id'), table_name='admin_config_logs')
    op.drop_index(op.f('ix_admin_config_logs_key'), table_name='admin_config_logs')
    op.drop_table('admin_config_logs')
    op.drop_index(op.f('ix_recharge_orders_id'), table_name='recharge_orders')
    op.drop_index(op.f('ix_recharge_orders_order_no'), table_name='recharge_orders')
    op.drop_index(op.f('ix_recharge_orders_user_id'), table_name='recharge_orders')
    op.drop_table('recharge_orders')
    op.drop_index(op.f('ix_user_balances_id'), table_name='user_balances')
    op.drop_index(op.f('ix_user_balances_user_id'), table_name='user_balances')
    op.drop_table('user_balances')
    op.drop_index(op.f('ix_reconciliation_reports_id'), table_name='reconciliation_reports')
    op.drop_index(op.f('ix_reconciliation_reports_report_date'), table_name='reconciliation_reports')
    op.drop_table('reconciliation_reports')
    op.add_column('orders', sa.Column('payment_platform', sa.String(length=10), nullable=True))
    op.add_column('orders', sa.Column('wx_transaction_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('prepay_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('payment_time', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('refund_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('refund_time', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('pay_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'pay_time')
    op.drop_column('orders', 'refund_time')
    op.drop_column('orders', 'refund_id')
    op.drop_column('orders', 'payment_time')
    op.drop_column('orders', 'prepay_id')
    op.drop_column('orders', 'transaction_id')
    op.drop_column('orders', 'wx_transaction_id')
    op.drop_column('orders', 'payment_platform')
    op.create_table('reconciliation_reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('total_orders', sa.INTEGER(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('total_refunds', sa.INTEGER(), nullable=False),
    sa.Column('refund_amount', sa.FLOAT(), nullable=False),
    sa.Column('net_income', sa.FLOAT(), nullable=False),
    sa.Column('platform_fee', sa.FLOAT(), nullable=False),
    sa.Column('promoter_commission', sa.FLOAT(), nullable=False),
    sa.Column('diff_count', sa.INTEGER(), nullable=False),
    sa.Column('diff_details', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_reports_report_date'), 'reconciliation_reports', ['report_date'], unique=1)
    op.create_index(op.f('ix_reconciliation_reports_id'), 'reconciliation_reports', ['id'], unique=False)
    op.create_table('user_balances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('total_recharged', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('total_consumed', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('frozen_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('version', sa.BIGINT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_balances_user_id'), 'user_balances', ['user_id'], unique=1)
    op.create_index(op.f('ix_user_balances_id'), 'user_balances', ['id'], unique=False)
    op.create_table('recharge_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('order_no', sa.VARCHAR(length=64), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('platform', sa.VARCHAR(length=10), nullable=False),
    sa.Column('prepay_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recharge_orders_user_id'), 'recharge_orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_recharge_orders_order_no'), 'recharge_orders', ['order_no'], unique=1)
    op.create_index(op.f('ix_recharge_orders_id'), 'recharge_orders', ['id'], unique=False)
    op.create_table('admin_config_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('old_value', sa.TEXT(), nullable=True),
    sa.Column('new_value', sa.TEXT(), nullable=True),
    sa.Column('operator', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_config_logs_key'), 'admin_config_logs', ['key'], unique=False)
    op.create_index(op.f('ix_admin_config_logs_id'), 'admin_config_logs', ['id'], unique=False)
    op.create_table('balance_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('balance_before', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('direction', sa.VARCHAR(length=10), nullable=False),
    sa.Column('biz_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('biz_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_logs_user_id'), 'balance_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_balance_logs_id'), 'balance_logs', ['id'], unique=False)
    op.create_index(op.f('idx_balance_logs_user_time'), 'balance_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('admin_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_config_key'), 'admin_config', ['key'], unique=1)
    op.create_index(op.f('ix_admin_config_id'), 'admin_config', ['id'], unique=False)
    op.create_table('invoice_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('tax_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('remark', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_requests_user_id'), 'invoice_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_invoice_requests_order_id'), 'invoice_requests', ['order_id'], unique=False)
    op.create_index(op.f('ix_invoice_requests_id'), 'invoice_requests', ['id'], unique=False)
    # ### end Alembic commands ###
