"""add_soft_delete_fields

Revision ID: c0398919c9e1
Revises: 02c9e16c4b58
Create Date: 2026-05-27 07:42:58.551623

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0398919c9e1"
down_revision: str | Sequence[str] | None = "02c9e16c4b58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("version", sa.BigInteger(), nullable=False, server_default=sa.text("1"), comment="乐观锁版本号"),
    )
    op.add_column("orders", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("orders", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column(
        "products",
        sa.Column("version", sa.BigInteger(), nullable=False, server_default=sa.text("1"), comment="乐观锁版本号"),
    )
    op.add_column("products", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("products", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column(
        "users",
        sa.Column("version", sa.BigInteger(), nullable=False, server_default=sa.text("1"), comment="乐观锁版本号"),
    )
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column(
        "withdrawals",
        sa.Column("version", sa.BigInteger(), nullable=False, server_default=sa.text("1"), comment="乐观锁版本号"),
    )
    op.add_column("withdrawals", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("withdrawals", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("withdrawals", "is_deleted")
    op.drop_column("withdrawals", "deleted_at")
    op.drop_column("withdrawals", "version")
    op.drop_column("users", "is_deleted")
    op.drop_column("users", "deleted_at")
    op.drop_column("users", "version")
    op.drop_column("products", "is_deleted")
    op.drop_column("products", "deleted_at")
    op.drop_column("products", "version")
    op.drop_column("orders", "is_deleted")
    op.drop_column("orders", "deleted_at")
    op.drop_column("orders", "version")
    # ### end Alembic commands ###
